pimcore:
    general:
        valid_languages: 'en,de,fr'
        domain: 'foo.com'

    chromium:
        uri: 'ws://chrome:3000/'

    gotenberg:
        base_url: 'http://gotenberg:3000'

pimcore_open_search_client:
    clients:
        default:
            hosts: ['https://opensearch:9200']
            password: 'XkxGSdN0sMdq9OS'
            username: 'admin'
            ssl_verification: false