pimcore_data_importer:
    messenger_queue_processing:
        activated: true
        worker_item_count: 150

advanced_object_search:
    index_name_prefix: 'advanced_object_search_'
    es_hosts:
        - 'elastic'
    messenger_queue_processing:
        activated: true

pimcore_portal_engine:
    messenger_queue_processing:
        activated: true
    custom_public_routes:
        - pimcore_saas_ping
        - pimcore_saas_monitoring
        - pimcore_saas_update_preparation_cli_maintenance
        - pimcore_saas_update_preparation_ready
        - pimcore_openidconnect_buttoninjection_script
        - admin_pimcoredatahub_webservice
        - data_hub_simple_rest_swagger
        - pimcore_datahubsimplerest_swagger_swaggerconfiguration
        - datahub_productsup_datapull
        - pimcore_datahubproductsup_productsup_orderpush

pimcore_data_hub_simple_rest:
    messenger_queue_processing:
        activated: true
    # Prefix for index names
    index_name_prefix:    datahub_restindex_
    # Limit of page size and offset when paging only works via page cursor (and not page numbers anymore). Limit 10000 comes from Elasticsearch.
    max_results_window:   10000
    es_hosts:
        - 'elastic'
    indexing_options:
        assets:
            enable_exif: false
            enable_xmp: false
            enable_iptc: false
        global_options:
            numeric_detection: false
            date_detection: false
