pimcore_data_importer:
    messenger_queue_processing:
        activated: true
        worker_item_count: 150

pimcore_data_hub_simple_rest:
    messenger_queue_processing:
        activated: true
    # Prefix for index names
    index_name_prefix:    datahub_restindex_
    # Limit of page size and offset when paging only works via page cursor (and not page numbers anymore). Limit 10000 comes from Elasticsearch.
    max_results_window:   10000
    indexing_options:
        assets:
            enable_exif: false
            enable_xmp: false
            enable_iptc: false
        global_options:
            numeric_detection: false
            date_detection: false
