pimcore_portal_engine:


    custom_public_routes:
        - pimcore_saas_ping
        - pimcore_saas_monitoring
        - pimcore_saas_update_preparation_cli_maintenance
        - pimcore_saas_update_preparation_ready
        - pimcore_openidconnect_buttoninjection_script
        - admin_pimcoredatahub_webservice
        - data_hub_simple_rest_swagger
        - pimcore_datahubsimplerest_swagger_swaggerconfiguration
        - datahub_productsup_datapull
        - pimcore_datahubproductsup_productsup_orderpush

