# CI overrides: remove debug services, use ephemeral storage, reduce memory
services:
    db:
        ports: []
        volumes: []

    opensearch:
        volumes: []
        environment:
            - cluster.name=opensearch-cluster
            - node.name=opensearch-node
            - discovery.seed_hosts=opensearch-node
            - cluster.routing.allocation.disk.threshold_enabled=false
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m"
            - discovery.type=single-node
            - action.auto_create_index=false
            - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD:-gBsVe!Dut723}

    opensearch-dashboards:
        profiles:
            - debug

    mailpit:
        profiles:
            - debug

    mercure:
        ports:
            - "8080:80"

volumes:
    pimcore-it-database: {}
    pimcore-it-opensearch: {}
