name: Run Pimcore Integration Tests

on:
    workflow_dispatch: 
        inputs:
            test_branch:
                description: 'Used branch of k6 tests'
                required: false
                type: string
    schedule:
        - cron: '0 3 * * 1,3,5'

jobs:
  run-integration-test:  
    runs-on: arc-runner-set
    steps:
    - name: "Setup docker"
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc
        
        # Add the repository to Apt sources:
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    - name: "Verify Docker"
      run: |
        sudo docker run hello-world
     
    - name: "Checkout platform version"
      uses: actions/checkout@v2
      with:
        path: './platform-version'

    - name: "Checkout K6 Tests"
      uses: "actions/checkout@v3"
      with:
          repository: "pimcore/saas-k6"
          ref: ${{ inputs.test_branch || github.ref_name }}
          path: "./platform-version-working-dir/saas-k6"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Setup environment
      working-directory: "./platform-version-working-dir"
      run: |
          chmod 755 ../platform-version/.github/scripts/01-setup-environment.sh 
          ../platform-version/.github/scripts/01-setup-environment.sh ${{ secrets.ENTERPRISE_REPOSITORY_TOKEN }}

    - name: Install Pimcore
      working-directory: "./platform-version-working-dir/test-project"
      run: |
          chmod 755 ../../platform-version/.github/scripts/02-install-pimcore.sh
          ../../platform-version/.github/scripts/02-install-pimcore.sh

    - name: Run Tests
      working-directory: "./platform-version-working-dir"
      run: |
          chmod 755 ../platform-version/.github/scripts/03-run-tests.sh
          ../platform-version/.github/scripts/03-run-tests.sh

    - name: Shutdown
      if: always()
      working-directory: "./platform-version-working-dir/test-project"
      run: |
          chmod 755 ../../platform-version/.github/scripts/04-shutdown.sh
          ../../platform-version/.github/scripts/04-shutdown.sh
