name: Run Pimcore Integration Tests

on:
    workflow_dispatch:
#    schedule:
#        - cron: '0 3 * * 1,3,5'

jobs:
  run-integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout platform version"
      uses: actions/checkout@v2
      with:
        path: './repos/pimcore/platform-version'

    - name: "Checkout K6 Tests"
      uses: "actions/checkout@v3"
      with:
          repository: "pimcore/saas-k6"
          path: "./repos/pimcore/saas-k6"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Setup environment
      run: |
          ./repos/pimcore/platform-version/.github/scripts/01-setup-environment.sh

    - name: Install Pimcore
      run: |
          ./repos/pimcore/platform-version/.github/scripts/02-install-pimcore.sh

    - name: Run Tests
      run: |
          ./repos/pimcore/platform-version/.github/scripts/03-run-tests.sh
