name: Run Pimcore Integration Tests

on:
    workflow_dispatch: 
        inputs:
            test_branch:
                description: 'Used branch of k6 tests'
                required: false
                type: string
    schedule:
        - cron: '0 3 * * 1,3,5'

jobs:
  run-integration-test:  
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout platform version"
      uses: actions/checkout@v2
      with:
        path: './platform-version'

    - name: "Checkout K6 Tests"
      uses: "actions/checkout@v3"
      with:
          repository: "pimcore/saas-k6"
          ref: ${{ inputs.test_branch || github.ref_name }}
          path: "./platform-version-working-dir/saas-k6"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Setup environment
      working-directory: "./platform-version-working-dir"
      run: |
          chmod 755 ../platform-version/.github/scripts/01-setup-environment.sh 
          ../platform-version/.github/scripts/01-setup-environment.sh ${{ secrets.ENTERPRISE_REPOSITORY_TOKEN }}

    - name: Install Pimcore
      working-directory: "./platform-version-working-dir/test-project"
      run: |
          chmod 755 ../../platform-version/.github/scripts/02-install-pimcore.sh
          ../../platform-version/.github/scripts/02-install-pimcore.sh

    - name: Run Tests
      working-directory: "./platform-version-working-dir"
      run: |
          chmod 755 ../platform-version/.github/scripts/03-run-tests.sh
          ../platform-version/.github/scripts/03-run-tests.sh

    - name: Shutdown
      if: always()
      working-directory: "./platform-version-working-dir/test-project"
      run: |
          chmod 755 ../../platform-version/.github/scripts/04-shutdown.sh
          ../../platform-version/.github/scripts/04-shutdown.sh
