name: Run Pimcore Integration Tests

on:
    workflow_dispatch:
#    schedule:
#        - cron: '0 3 * * 1,3,5'

jobs:
  run-integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout platform version"
      uses: actions/checkout@v2
      with:
        path: './platform-version'

    - name: "Checkout K6 Tests"
      uses: "actions/checkout@v3"
      with:
          repository: "pimcore/saas-k6"
          ref: "pimcore-10"
          path: "./platform-version-working-dir/saas-k6"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Setup environment
      run: |
          chmod 755 ./repos/pimcore/platform-version/.github/scripts/01-setup-environment.sh 
          ./repos/pimcore/platform-version/.github/scripts/01-setup-environment.sh

    - name: Install Pimcore
      working-directory: "./test-project"
      run: |
          chmod 755 ./repos/pimcore/platform-version/.github/scripts/02-install-pimcore.sh
          ./repos/pimcore/platform-version/.github/scripts/02-install-pimcore.sh

    - name: Run Tests
      working-directory: "./test-project"
      run: |
          chmod 755 ./repos/pimcore/platform-version/.github/scripts/03-run-tests.sh
          ./repos/pimcore/platform-version/.github/scripts/03-run-tests.sh

    - name: Shutdown
      working-directory: "./test-project"
      run: |
          chmod 755 ./repos/pimcore/platform-version/.github/scripts/04-shutdown.sh
          ./repos/pimcore/platform-version/.github/scripts/04-shutdown.sh
