name: Run OSV-Scanner

on:
    workflow_dispatch:
    schedule:
        - cron: '0 3 * * *'

permissions:
  contents: read

jobs:
    composer-checks:
        uses: pimcore/workflows-collection-public/.github/workflows/reusable-osv-checks.yaml@osv_reusable
        strategy:
            fail-fast: false
            matrix:
                include:
                    - { php-version: 8.1, platform-version: '2022.0' }
                    - { php-version: 8.2, platform-version: '2023.3' }
                    - { php-version: 8.4, platform-version: '2024.4' }
        with:
            php-version: ${{ matrix.php-version }}
            platform-version: ${{ matrix.platform-version }}
        secrets: inherit