name: Generate SBOM

on:
  push:
    tags:
      - "v[0-9][0-9][0-9][0-9].[0-9]*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sbom:
    uses: pimcore/workflows-collection-public/.github/workflows/reusable-sbom.yaml@fix/sbom-merge-cli-flag
    with:
      promote-conflicts: true
      private-packagist: true
    secrets:
      SSH_PRIVATE_KEY_PIMCORE_DEPLOYMENTS_USER: ${{ secrets.SSH_PRIVATE_KEY_PIMCORE_DEPLOYMENTS_USER }}
      COMPOSER_PIMCORE_REPO_PACKAGIST_TOKEN: ${{ secrets.COMPOSER_PIMCORE_REPO_PACKAGIST_TOKEN }}